### ISSUE TITLE
Add support for Autogazelle

### ISSUE THREAD

**Issue by philwo** [philwo/bazelisk#1]
See https://github.com/bazelbuild/bazel-gazelle/tree/master/cmd/autogazelle

**Comment by akshayjshah** [comment]
Not sure if you want a separate issue for this, but it also appears that bazelisk prevents Bazel from correctly delegating to `tools/bazel`.

**Comment by akshayjshah** [comment]
Thanks for reviewing and merging so many PRs this morning, @philwo!
