### ISSUE TITLE
Ready for broad use?

### ISSUE THREAD

**Issue by mpassell** [philwo/bazelisk#35]
(Really a question more than an issue)
I'm part of a team with plans to finish a large Maven-to-Bazel migration in the next month or so. One of the last things that's been worrying me was how to handle the nice (but scarily quick) Bazel release cadence. When I saw that Bazelisk allows you to pin people to a specific version and handle the downloading/set-up, I was super excited. Would you feel comfortable rolling it out to a team of over 100 engineers at this point or do you think I should wait for it to stabilize?

**Comment by mpassell** [comment]
I've recruited three others and myself to start using it and it's been working flawlessly so far. Yay!

**Comment by philwo** [comment]
Hi @mpassell,

thanks for bringing this up. Yes, I think it's stable and ready to be used at that scale. We've also deployed the Go version of Bazelisk as the default "bazel" command on Bazel's CI recently, so it gets exercised there under real load.

If you can, I'd recommend to use the Go version, as it's the current focus of new development, has a few more features and a bit more polish than the Python version, but I do aim to maintain the Python version to be at the same level of reliability and bug fixes.

If you stumble across any issues or need some feature, just file an issue or send a PR here. I'll gladly help you out!

Cheers,
Philipp

**Comment by mpassell** [comment]
Excellent! I was already leaning toward the Go version due to ease of deployment, so that works for me. I'll close this. With luck, others will find this if they have the same question.
