### ISSUE TITLE
Release binaries not set as executable

### ISSUE THREAD

**Issue by mpassell** [philwo/bazelisk#37]
Would it be easy to set the executable bits on the release binaries so that they don't have to be chmod'd after downloading?

**Comment by mpassell** [comment]
When I [ran this](https://github.com/philwo/bazelisk/blob/38961f1371da7ef74dd88f897ed4178f5c6602a4/build.sh#L6) locally, the resulting file was marked as executable (as I would have expected), so who knows what the problem is...

**Comment by mpassell** [comment]
This is pretty easy to work around, so I'd be fine with closing this, unless it's easy to fix. In the meantime, I created this install script for my co-workers:
```
#!/usr/bin/env bash

set -euo pipefail

VERSION="0.0.1"
TEMP_FILE="/tmp/bazel"
INSTALL_DIR="/usr/local/bin"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    INSTALL_FILE="bazelisk-linux-amd64";
    MV_CMD="sudo mv";
elif [[ "$OSTYPE" == "darwin"* ]]; then
    INSTALL_FILE="bazelisk-darwin-amd64";
    MV_CMD="mv";
else
    echo "unsupported OS ${OSTYPE}";
    exit -1;
fi

curl -fL -o ${TEMP_FILE} https://github.com/philwo/bazelisk/releases/download/v${VERSION}/${INSTALL_FILE}
chmod +x ${TEMP_FILE}
${MV_CMD} ${TEMP_FILE} ${INSTALL_DIR}
```

**Comment by winstonlou1** [comment]
Hi mpassell, I am trying to install bazelisk and bazel onto my Windows pc but I am not able to manually locate the usr/local/bin folder location.

This is similar to your pipe script: INSTALL_DIR="/usr/local/bin"

Are you happy to assist/advise?

**Comment by mpassell** [comment]
Hi @winstonlou1 . I've never tried to run Bazelisk in Windows, but you could try downloading the latest version (currently https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-windows-amd64.exe ) and putting the file somewhere in your path.
