### ISSUE TITLE
ctrl-c during download leaves you in a broken state

### ISSUE THREAD

**Issue by keith** [philwo/bazelisk#43]
I control-c'd during the download of a new bazel version, and the next time I ran bazelisk I was hit with:

```
% bazelisk test //test/exe:main_common_test --define=google_grpc=disabled --define=signal_trace=disabled --define=tcmalloc=disabled
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/keith/dev/envoy/tools/bazel.rc
file is invalid or corrupted (missing end of central directory record)
Cannot find central directory
FATAL: Failed to open Bazel as a zip file: (error: 5): Input/output error
```

In order to fix this I had to `rm -rf ~/.bazelisk` and run it again

**Comment by philwo** [comment]
Sorry for the problems, @keith.

In the Go version of Bazelisk this is already fixed, by first downloading to a temporary file and only renaming it on success.

I'll add the fix to the Python version, too.

**Comment by philwo** [comment]
Fixed in https://github.com/philwo/bazelisk/pull/49 :)
