### ISSUE TITLE
Wants to download bazel 0.18.1 as latest version

### ISSUE THREAD

**Issue by Globegitter** [philwo/bazelisk#7]
Bazel 0.18.1 was released after 0.19.0 and now when there is no `.bazelversion` supplied bazeilsk is trying to download 0.18.1. My feeling would be that we would want it to download 0.19.0. But what do you think?

**Comment by philwo** [comment]
I agree - it should download the "really latest" version, not what GitHub thinks is the latest based on when the tag was created.

**Comment by philwo** [comment]
This was fixed by @natpen in https://github.com/philwo/bazelisk/pull/8
